const PATHS=['modernization','new_site','migration','focused_improvement','research'];
const STAGES=['discovery','evidence','scope','design','implementation','qa','review','deployment','maintenance'];
const now=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID();
const LEASE=15*60*1000;
export class HttpError extends Error {constructor(status,message,code='request_error'){super(message);this.status=status;this.code=code;}}
const fail=(status,message,code)=>{throw new HttpError(status,message,code)};
export const json=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const text=(value,label,max=8000,required=false)=>{if(value===undefined&&!required)return '';if(typeof value!=='string'||value.length>max||(required&&!value.trim()))fail(400,`${label} must be ${required?'non-empty ':''}text of at most ${max} characters.`);return value.trim()};
const choice=(value,allowed,label)=>{if(!allowed.includes(value))fail(400,`Invalid ${label}.`);return value};
const repoName=(s)=>{s=text(s,'Repository name',100,true);if(!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(s))fail(400,'Invalid repository name.');return s};
const sha=(s)=>{if(typeof s!=='string'||!/^[a-f0-9]{40}$/.test(s))fail(400,'A full 40-character Git commit is required.');return s};
async function body(request){if(!request.headers.get('content-type')?.startsWith('application/json'))fail(415,'Use application/json.');const length=Number(request.headers.get('content-length')||0);if(length>524288)fail(413,'Request is too large.');const reader=request.body?.getReader();let bytes=0,parts=[];if(reader){while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>524288){await reader.cancel();fail(413,'Request is too large.')}parts.push(value)}}const all=new Uint8Array(bytes);let offset=0;for(const p of parts){all.set(p,offset);offset+=p.length}try{const v=JSON.parse(new TextDecoder().decode(all));if(!v||typeof v!=='object'||Array.isArray(v))throw Error();return v}catch{fail(400,'Invalid JSON object.')}}
async function equalSecret(a,b){const encoder=new TextEncoder();const hashes=await Promise.all([a,b].map(v=>crypto.subtle.digest('SHA-256',encoder.encode(v))));let d=0;const x=new Uint8Array(hashes[0]),y=new Uint8Array(hashes[1]);for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0;}
export async function authorize(request,env,ctx){
 const path=new URL(request.url).pathname;
 if(path.startsWith('/api/runner/')){const token=request.headers.get('authorization')?.replace(/^Bearer /,'');if(!env.RUNNER_TOKEN||env.RUNNER_TOKEN.length<32||!token||!await equalSecret(token,env.RUNNER_TOKEN))fail(401,'Runner authentication required.');return {runner:true};}
 if(!ctx?.access)fail(401,'Sign in through Cloudflare Access.','sign_in_required');
 const identity=await ctx.access.getIdentity();const owners=(env.OWNER_EMAILS||'').toLowerCase().split(',').map(x=>x.trim()).filter(Boolean);
 if(!identity?.email||!owners.includes(identity.email.toLowerCase()))fail(403,'This workspace is private.');
 if(!['GET','HEAD'].includes(request.method)){const origin=request.headers.get('origin');if(origin!==new URL(request.url).origin)fail(403,'Same-origin requests required.');}
 return {email:identity.email};
}
const stmt=(env,sql,...params)=>env.DB.prepare(sql).bind(...params);
const one=(env,sql,...params)=>stmt(env,sql,...params).first();
const rows=async(env,sql,...params)=>(await stmt(env,sql,...params).all()).results;
const run=(env,sql,...params)=>stmt(env,sql,...params).run();
const event=(env,action,detail)=>run(env,'INSERT INTO events VALUES (?,?,?,?)',uid(),action,detail,now());
const decodeTask=t=>t?{...t,context_ids:JSON.parse(t.context_ids),assignments:JSON.parse(t.assignments)}:null;
function publicRun(r){if(!r)return null;const {lease_token,lease_until,packet_json,...data}=r;return {...data,tests:r.tests?JSON.parse(r.tests):null};}
async function project(env,id){const p=await one(env,'SELECT * FROM projects WHERE id=?',id);if(!p)fail(404,'Project not found.');return p;}
async function task(env,id){const t=decodeTask(await one(env,'SELECT * FROM tasks WHERE id=?',id));if(!t)fail(404,'Task not found.');return t;}
async function packet(env,id){const t=await task(env,id);const p=await project(env,t.project_id);const contexts=[];for(const cid of t.context_ids){const c=await one(env,'SELECT * FROM contexts WHERE id=? AND project_id=?',cid,p.id);if(c)contexts.push(c);else fail(409,'Selected context was removed. Create a revised task before starting a run.');}return {version:1,project:p,task:t,contexts,constraints:{human_review:true,auto_merge:false,auto_deploy:false,context_policy:'Only the explicitly selected context is included.'}};}
function binding(env){if(!env.ARTIFACTS)fail(503,'Artifacts is not connected. Configure the Worker binding.','artifacts_unavailable');return env.ARTIFACTS;}
async function withRepo(env,name,fn){let repo;try{repo=await binding(env).get(repoName(name));return await fn(repo);}catch(e){if(e instanceof HttpError)throw e;fail(503,'Artifacts could not complete this request. Check repository readiness and account access.','artifacts_unavailable');}finally{repo?.[Symbol.dispose]?.();}}
const repoInfo=r=>({name:r.name,description:r.description||'',default_branch:r.defaultBranch||r.default_branch||'main',remote:r.remote||'',status:r.status||'ready',created_at:r.createdAt||r.created_at||null});
async function repos(env,cursor){try{const result=await binding(env).list({limit:50,...(cursor?{cursor}:{})});return {repos:result.repos.map(repoInfo),cursor:result.cursor||null}}catch(e){if(e instanceof HttpError)throw e;fail(503,'Artifacts service is unavailable. Verify account access and the namespace.','artifacts_unavailable');}}
async function connections(env){let artifacts;try{await repos(env);artifacts={status:'connected',detail:'Cloudflare Artifacts binding responded successfully.'}}catch{artifacts={status:'unavailable',detail:'Artifacts access has not been verified. Project planning and task packets remain available.'}}const runner=await one(env,'SELECT * FROM runners ORDER BY last_seen DESC LIMIT 1');const active=runner&&Date.parse(runner.last_seen)>Date.now()-120000;return {artifacts,amplifier:{status:active?'connected':'not_connected',detail:active?'Runner heartbeat received. Execution results are verified separately.':'Pair the outbound runner in your isolated Amplifier environment.',last_seen:runner?.last_seen||null},github:{status:'linked',detail:'Project links only. GitHub authentication, imports and push synchronization are not connected.'},context_intelligence:{status:'not_connected',detail:'No connection to your Pi graph or session history. Add selected evidence manually.'}};}
async function state(env,owner){await expireRuns(env);const [projects,tasks,contexts,runs,events]=await Promise.all([rows(env,'SELECT * FROM projects ORDER BY created_at'),rows(env,'SELECT * FROM tasks ORDER BY created_at DESC'),rows(env,'SELECT * FROM contexts ORDER BY created_at DESC'),rows(env,'SELECT * FROM runs ORDER BY created_at DESC'),rows(env,'SELECT * FROM events ORDER BY created_at DESC LIMIT 100')]);return {version:'0.1.0',owner:owner.email,projects,tasks:tasks.map(decodeTask),contexts,runs:runs.map(publicRun),events,connections:await connections(env)};}
async function expireRuns(env){await run(env,"UPDATE runs SET status='failed',summary='Runner lease expired. No result was accepted.',finished_at=? WHERE status='running' AND lease_until<?",now(),Date.now());}

async function ownerApi(request,env,owner,url){const path=url.pathname,method=request.method;let match;
 if(method==='GET'&&(path==='/api/state'||path==='/api/export'))return json(await state(env,owner));
 if(method==='POST'&&path==='/api/projects'){const b=await body(request);let github_url=text(b.github_url,'GitHub URL',400);if(github_url&&!/^https:\/\/github\.com\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/?$/.test(github_url))fail(400,'Use a GitHub repository URL without credentials or query parameters.');const p={id:uid(),name:text(b.name,'Name',120,true),description:text(b.description,'Description'),github_url,path:choice(b.path||'modernization',PATHS,'delivery path'),stage:'discovery',repo_name:null,created_at:now()};await run(env,'INSERT INTO projects VALUES (?,?,?,?,?,?,?,?)',...Object.values(p));await event(env,'Project created',p.name);return json(p,201);}
 if(method==='PATCH'&&(match=path.match(/^\/api\/projects\/([^/]+)$/))){const p=await project(env,match[1]);const b=await body(request);if(b.repo_name!==undefined){const name=repoName(b.repo_name);await withRepo(env,name,r=>r.info());await run(env,'UPDATE projects SET repo_name=? WHERE id=?',name,p.id);}if(b.stage!==undefined){choice(b.stage,STAGES,'stage');await run(env,'UPDATE projects SET stage=? WHERE id=?',b.stage,p.id);await event(env,'Stage selected',`${p.name}: ${b.stage}. Selection does not start agents or deployment.`);}return json(await project(env,p.id));}
 if(method==='POST'&&path==='/api/contexts'){const b=await body(request);await project(env,text(b.project_id,'Project',100,true));const c={id:uid(),project_id:b.project_id,title:text(b.title,'Title',160,true),kind:choice(b.kind||'evidence',['evidence','decision','hypothesis','reference','memory'],'context kind'),content:text(b.content,'Context content',24000,true),source:text(b.source,'Source',1000),created_at:now()};await run(env,'INSERT INTO contexts VALUES (?,?,?,?,?,?,?)',...Object.values(c));return json(c,201);}
 if(method==='DELETE'&&(match=path.match(/^\/api\/contexts\/([^/]+)$/))){await run(env,'DELETE FROM contexts WHERE id=?',match[1]);return json({ok:true});}
 if(method==='POST'&&path==='/api/tasks'){const b=await body(request);const p=await project(env,text(b.project_id,'Project',100,true));if(!Array.isArray(b.context_ids)||b.context_ids.length>20||new Set(b.context_ids).size!==b.context_ids.length)fail(400,'Choose up to 20 distinct context items.');for(const id of b.context_ids){if(typeof id!=='string'||!await one(env,'SELECT id FROM contexts WHERE id=? AND project_id=?',id,p.id))fail(400,'Context must belong to this project.');}if(!Array.isArray(b.assignments)||b.assignments.length<1||b.assignments.length>2)fail(400,'Choose one or two agent assignments.');const assignments=b.assignments.map(a=>({role:text(a.role,'Role',80,true),instruction:text(a.instruction,'Assignment',8000,true)}));const t={id:uid(),project_id:p.id,title:text(b.title,'Task title',160,true),goal:text(b.goal,'Goal',16000,true),acceptance:text(b.acceptance,'Acceptance criteria',8000,true),scope:text(b.scope,'Scope',8000,true),context_ids:JSON.stringify(b.context_ids),assignments:JSON.stringify(assignments),status:'draft',created_at:now()};await run(env,'INSERT INTO tasks VALUES (?,?,?,?,?,?,?,?,?,?)',...Object.values(t));await event(env,'Task prepared',t.title);return json(decodeTask(t),201);}
 if(method==='GET'&&(match=path.match(/^\/api\/tasks\/([^/]+)\/packet$/)))return json(await packet(env,match[1]));
 if(method==='POST'&&(match=path.match(/^\/api\/tasks\/([^/]+)\/queue$/))){await body(request);const t=await task(env,match[1]);const p=await project(env,t.project_id);if(t.status!=='draft')fail(409,'This task has already been queued. Create a revised task for another attempt.');if(!p.repo_name)fail(409,'Create or link an Artifacts repository to this project first.');const c=await connections(env);if(c.amplifier.status!=='connected')fail(409,'Pair an Amplifier runner before queuing work.');const base=await withRepo(env,p.repo_name,async r=>{const info=await r.info();const commits=await r.log({ref:info.defaultBranch||info.default_branch||'main',limit:1});if(!commits.length)fail(409,'Push an initial commit to the project repository first.');return sha(commits[0].hash);});const snapshot=JSON.stringify({...await packet(env,t.id),project:p});if(snapshot.length>200000)fail(400,'Selected context exceeds the 200 KB task packet limit.');const created=t.assignments.map(a=>({id:uid(),role:a.role,instruction:a.instruction}));const saved=await env.DB.batch([...created.map(r=>stmt(env,"INSERT INTO runs (id,task_id,project_id,role,instruction,repo_name,base_commit,packet_json,created_at) SELECT ?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM tasks WHERE id=? AND status='draft')",r.id,t.id,p.id,r.role,r.instruction,`run-${r.id}`,base,snapshot,now(),t.id)),stmt(env,"UPDATE tasks SET status='queued' WHERE id=? AND status='draft'",t.id)]);if(!saved[saved.length-1].meta.changes)fail(409,'This task was queued by another request.');await event(env,'Work queued',`${t.title}: ${created.length} isolated assignments`);return json({runs:(await rows(env,'SELECT * FROM runs WHERE task_id=?',t.id)).map(publicRun)},201);}
 if(method==='GET'&&path==='/api/repos')return json(await repos(env,url.searchParams.get('cursor')));
 if(method==='POST'&&path==='/api/repos'){const b=await body(request);const name=repoName(b.name);if(b.project_id)await project(env,b.project_id);let created;try{created=await binding(env).create(name,{description:text(b.description,'Description',1000),setDefaultBranch:'main',readOnly:false});}catch(e){if(e instanceof HttpError)throw e;fail(503,'Repository creation failed. Check access or use a unique name.');}if(b.project_id)await run(env,'UPDATE projects SET repo_name=? WHERE id=?',name,b.project_id);await event(env,'Repository created',name);return json(repoInfo(created),201);}
 if(method==='GET'&&(match=path.match(/^\/api\/repos\/([^/]+)\/log$/))){const ref=text(url.searchParams.get('ref')||'HEAD','Ref',200,true);return json({commits:await withRepo(env,match[1],r=>r.log({ref,limit:50}))});}
 if(method==='GET'&&(match=path.match(/^\/api\/repos\/([^/]+)\/file$/))){const ref=text(url.searchParams.get('ref')||'HEAD','Ref',200,true),filePath=text(url.searchParams.get('path'),'File path',1000,true);if(filePath.startsWith('/')||filePath.split('/').includes('..'))fail(400,'Use a repository-relative path.');const content=await withRepo(env,match[1],async r=>{const file=await r.readFile({ref,path:filePath});if(!file)fail(404,'File not found.');if(file.size>200000)fail(413,'File preview limit is 200 KB.');return file.text()});return json({content,path:filePath,ref});}
 if(method==='POST'&&(match=path.match(/^\/api\/runs\/([^/]+)\/review$/))){const b=await body(request);const r=await one(env,'SELECT * FROM runs WHERE id=?',match[1]);if(!r)fail(404,'Run not found.');if(r.status!=='review_ready')fail(409,'Only completed contributions can be reviewed.');if(b.expected_head!==r.head_commit)fail(409,'The contribution changed. Refresh and review its current commit.');const decision=choice(b.decision,['accepted','rejected','revision_requested'],'review decision');if(decision==='accepted'){const tests=JSON.parse(r.tests||'{}');if(tests.passed!==true)fail(409,'Acceptance requires passing test evidence.');const snapshot=JSON.parse(r.packet_json);const source=await withRepo(env,snapshot.project.repo_name,x=>x.log({ref:'HEAD',limit:1}));if(source[0]?.hash!==r.base_commit)fail(409,'The source repository changed since this task began. Refresh the task against the new base.');const live=await withRepo(env,r.repo_name,x=>x.log({ref:'HEAD',limit:1}));if(live[0]?.hash!==r.head_commit)fail(409,'Repository head changed since the report. Request a new verified contribution.');}const result=await run(env,"UPDATE runs SET status=?,review_note=?,reviewed_at=? WHERE id=? AND status='review_ready' AND head_commit=?",decision,text(b.note,'Review note',8000),now(),r.id,r.head_commit);if(!result.meta.changes)fail(409,'Another review already updated this contribution.');await event(env,'Review recorded',`${r.role}: ${decision}. No merge or deployment performed.`);return json(publicRun(await one(env,'SELECT * FROM runs WHERE id=?',r.id)));}
 fail(404,'Endpoint not found.');
}

async function runnerApi(request,env,url){if(request.method!=='POST')fail(405,'Use POST.');const b=await body(request);let match;
 if(url.pathname==='/api/runner/heartbeat'){const id=text(b.runner_id,'Runner ID',100,true);await run(env,'INSERT INTO runners VALUES (?,?) ON CONFLICT(id) DO UPDATE SET last_seen=excluded.last_seen',id,now());return json({ok:true});}
 if(url.pathname==='/api/runner/claim'){const runner_id=text(b.runner_id,'Runner ID',100,true);await expireRuns(env);const token=uid()+uid();const claimed=await one(env,"UPDATE runs SET status='running',runner_id=?,lease_token=?,lease_until=?,started_at=? WHERE id=(SELECT id FROM runs WHERE status='queued' ORDER BY created_at LIMIT 1) AND status='queued' AND (SELECT count(*) FROM runs WHERE status='running')<2 RETURNING *",runner_id,token,Date.now()+LEASE,now());if(!claimed)return json({run:null});try{const snapshot=JSON.parse(claimed.packet_json);const sourceName=snapshot.project.repo_name;const fork=await withRepo(env,sourceName,r=>r.fork(claimed.repo_name,{description:`Task ${claimed.task_id}; role ${claimed.role}`,defaultBranchOnly:true,readOnly:false}));const scoped=await withRepo(env,claimed.repo_name,r=>r.createToken('write',3600));const repoToken=typeof scoped==='string'?scoped:scoped.plaintext||scoped.token;if(!repoToken)fail(503,'Artifacts token response was not recognized.');const refreshed=await one(env,"UPDATE runs SET lease_until=? WHERE id=? AND status='running' AND lease_token=? AND lease_until>=? RETURNING id",Date.now()+LEASE,claimed.id,token,Date.now());if(!refreshed)fail(409,'The run lease expired while its workspace was being prepared.');return json({run:{...publicRun(claimed),lease_token:token,lease_until:claimed.lease_until},packet:snapshot,repo:{remote:fork.remote,token:repoToken}});}catch(e){await run(env,"UPDATE runs SET status='failed',summary=?,finished_at=? WHERE id=?",'Workspace provisioning failed. Create a revised task after correcting Artifacts access.',now(),claimed.id);throw e;}}
 if((match=url.pathname.match(/^\/api\/runner\/runs\/([^/]+)\/(heartbeat|report)$/))){const r=await one(env,'SELECT * FROM runs WHERE id=?',match[1]);if(!r||r.status!=='running'||r.attempt!==b.attempt||!b.lease_token||!await equalSecret(b.lease_token,r.lease_token||'')||r.lease_until<Date.now())fail(409,'Run lease is stale or invalid.');if(match[2]==='heartbeat'){const updated=await run(env,"UPDATE runs SET lease_until=? WHERE id=? AND status='running' AND lease_token=? AND lease_until>=?",Date.now()+LEASE,r.id,r.lease_token,Date.now());if(!updated.meta.changes)fail(409,'Run lease expired.');return json({ok:true});}choice(b.status,['succeeded','failed'],'run status');const head=b.status==='succeeded'?sha(b.head_commit):null;const diff=text(b.diff,'Diff',120000);const summary=text(b.summary,'Summary',8000,true);const tests=JSON.stringify(b.tests||{});if(tests.length>64000)fail(400,'Test evidence exceeds 64 KB.');if(head){const commit=await withRepo(env,r.repo_name,x=>x.readCommit(head));if(!commit)fail(409,'Reported commit is not present in the assigned Artifacts repository.');const history=await withRepo(env,r.repo_name,x=>x.log({ref:head,limit:1000}));if(!history.some(c=>c.hash===r.base_commit))fail(409,'Reported commit does not descend from the approved base within the 1000-commit review bound.');}const update=await run(env,"UPDATE runs SET status=?,head_commit=?,diff=?,tests=?,summary=?,finished_at=? WHERE id=? AND status='running' AND lease_token=? AND lease_until>=?",head?'review_ready':'failed',head,diff,tests,summary,now(),r.id,r.lease_token,Date.now());if(!update.meta.changes)fail(409,'Run changed or lease expired during report.');await event(env,head?'Contribution ready':'Run failed',`${r.role}: ${summary.slice(0,200)}`);return json(publicRun(await one(env,'SELECT * FROM runs WHERE id=?',r.id)));}
 fail(404,'Runner endpoint not found.');
}
export async function handle(request,env,ctx){try{const actor=await authorize(request,env,ctx);if(!env.DB)fail(503,'Studio database is not configured.');const url=new URL(request.url);return actor.runner?await runnerApi(request,env,url):await ownerApi(request,env,actor,url);}catch(e){if(e instanceof HttpError)return json({error:e.message,code:e.code},e.status);return json({error:'The request could not be completed. Refresh before retrying.',code:'internal_error'},500);}}
